#if !UNITY_WEBGL
// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Nuskey.Net.Quic.Interop
{
    public static unsafe partial class NativeMethods
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "quic_http_handler";
#endif
        



        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate byte qhh_context_new_on_body_delegate(void* arg1, byte* arg2, nuint arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate byte qhh_context_new_on_headers_delegate(void* arg1, uint arg2, byte* arg3, nuint arg4);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate byte qhh_context_new_on_informational_headers_delegate(void* arg1, uint arg2, byte* arg3, nuint arg4);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate byte qhh_context_new_on_trailers_delegate(void* arg1, byte* arg2, nuint arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate byte qhh_context_set_qlog_callback_delegate(void* arg1, byte* arg2, nuint arg3, byte* arg4, nuint arg5);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate byte qhh_context_set_tls_options_verify_callback_delegate(void* arg1, byte* arg2, nuint arg3, byte* arg4, nuint arg5, byte* arg6, nuint arg7, byte arg8, int arg9, long arg10);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void qhh_context_new_on_complete_delegate(void* arg1, int arg2, int arg3, ulong arg4, byte* arg5, nuint arg6);



        [DllImport(__DllName, EntryPoint = "qhh_context_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern Context* qhh_context_new(int worker_threads, qhh_context_new_on_headers_delegate on_headers, qhh_context_new_on_body_delegate on_body, qhh_context_new_on_trailers_delegate on_trailers, qhh_context_new_on_informational_headers_delegate on_informational_headers, qhh_context_new_on_complete_delegate on_complete);

        [DllImport(__DllName, EntryPoint = "qhh_context_set_connection_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool qhh_context_set_connection_options(Context* context, ulong connect_timeout_ms, ulong handshake_timeout_ms, ulong pooled_connection_idle_timeout_ms, ulong pooled_connection_lifetime_ms, ulong dns_timeout_ms, ulong dns_refresh_timeout_ms, ulong happy_eyeballs_delay_ms, ulong keep_alive_ping_delay_ms, ulong keep_alive_ping_timeout_ms, [MarshalAs(UnmanagedType.U1)] bool keep_alive_ping_while_idle, nuint max_connections_per_server);

        [DllImport(__DllName, EntryPoint = "qhh_context_set_dns_override", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool qhh_context_set_dns_override(Context* context, byte* host_ptr, nuint host_len, byte* addresses_ptr, nuint addresses_len);

        [DllImport(__DllName, EntryPoint = "qhh_context_set_qlog", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool qhh_context_set_qlog(Context* context, void* state, qhh_context_set_qlog_callback_delegate callback);

        [DllImport(__DllName, EntryPoint = "qhh_context_set_http3_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool qhh_context_set_http3_options(Context* context, ulong max_header_list_size, ulong qpack_max_table_capacity, ulong qpack_blocked_streams, [MarshalAs(UnmanagedType.U1)] bool enable_extended_connect);

        [DllImport(__DllName, EntryPoint = "qhh_context_set_quic_flow_control", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool qhh_context_set_quic_flow_control(Context* context, ulong initial_max_data, ulong initial_max_stream_data_bidi_local, ulong initial_max_stream_data_bidi_remote, ulong initial_max_stream_data_uni, ulong initial_max_streams_bidi, ulong initial_max_streams_uni, ulong max_connection_window, ulong max_stream_window, nuint send_buffer_size, nuint receive_buffer_size);

        [DllImport(__DllName, EntryPoint = "qhh_context_set_quic_performance", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool qhh_context_set_quic_performance(Context* context, byte congestion_control, nuint initial_congestion_window_packets, [MarshalAs(UnmanagedType.U1)] bool enable_pacing, ulong max_pacing_rate, [MarshalAs(UnmanagedType.U1)] bool discover_path_mtu, byte pmtud_max_probes, [MarshalAs(UnmanagedType.U1)] bool enable_hystart, nuint max_send_udp_payload_size, nuint max_receive_udp_payload_size, ulong ack_delay_exponent, ulong max_ack_delay, double send_capacity_factor, [MarshalAs(UnmanagedType.U1)] bool enable_early_data);

        [DllImport(__DllName, EntryPoint = "qhh_context_set_tls_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool qhh_context_set_tls_options(Context* context, [MarshalAs(UnmanagedType.U1)] bool skip_verification, [MarshalAs(UnmanagedType.U1)] bool custom_verify, [MarshalAs(UnmanagedType.U1)] bool replace_default_roots, byte* override_name, nuint override_name_len, byte* roots, nuint roots_len, byte* client_certificates, nuint client_certificates_len, byte* client_key, nuint client_key_len, void* verify_state, qhh_context_set_tls_options_verify_callback_delegate verify_callback);

        [DllImport(__DllName, EntryPoint = "qhh_context_dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void qhh_context_dispose(Context* context);

        [DllImport(__DllName, EntryPoint = "qhh_context_get_pool_statistics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool qhh_context_get_pool_statistics(Context* context, nuint* connections, nuint* accepting_connections, nuint* idle_connections, nuint* active_requests, ulong* total_requests, ulong* early_data_attempts, ulong* early_data_accepted, ulong* early_data_rejected);

        [DllImport(__DllName, EntryPoint = "qhh_send", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern Request* qhh_send(Context* context, void* state, byte* method_ptr, nuint method_len, byte* host_ptr, nuint host_len, ushort port, byte* authority_ptr, nuint authority_len, byte* path_ptr, nuint path_len, byte* headers_ptr, nuint headers_len, [MarshalAs(UnmanagedType.U1)] bool has_body, [MarshalAs(UnmanagedType.U1)] bool allow_early_data);

        [DllImport(__DllName, EntryPoint = "qhh_request_write", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool qhh_request_write(Request* request, byte* data, nuint len);

        [DllImport(__DllName, EntryPoint = "qhh_request_finish", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void qhh_request_finish(Request* request);

        [DllImport(__DllName, EntryPoint = "qhh_request_cancel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void qhh_request_cancel(Request* request);

        [DllImport(__DllName, EntryPoint = "qhh_request_resume_body", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void qhh_request_resume_body(Request* request);

        [DllImport(__DllName, EntryPoint = "qhh_request_dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void qhh_request_dispose(Request* request);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Context
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Request
    {
    }



}
#endif